import { Person } from "./bai_1";
import { Student } from "./bai_2";
import { Car } from "./bai_3";
import { Rectangle } from "./bai_4";
import { BankAccount } from "./bai_5";
import { Book } from "./bai_6";
var person1 = new Person("Lê Hữu Phúc", 21);
var student2 = new Student("Lê Hữu Phúc", 21, "Sinh viên");
var car1 = new Car("Future", "Thể thao", "2022");
var r1 = new Rectangle(5, 4);
var acc = new BankAccount(1000);
var b = new Book("Tâm lý", "Lê Hữu", 2020);
console.log("----Thông tin----");
console.log(person1.toString());
console.log("----Thông tin sinh viên----");
console.log(student2.toString());
console.log("----Xe máy----");
car1.display();
console.log("----Hình chữ nhật----");
r1.display();
console.log("----Tài khoản ngân hàng----");
acc.displayBalance();
acc.getDeposit(500);
acc.getWithdraw(200);
acc.getWithdraw(2000);
console.log("----Thông tin sách----");
b.display();
